apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
  labels:
    app: webapp-angular
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp-angular
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-angular
        tier: backend
    spec:
      containers:
      - image: anvesh35/docker-with-dotnet:dotnet-v3434cbd
        name: dotnet
        env:
        - name: CORS_ORIGIN_URL
          value: http://angular-svc:4200
        ports:
        - containerPort: 5106