apiVersion: v1
kind: Service
metadata:
  name: dotnet-svc
spec:
  selector:
    app: webapp-angular
    tier: backend
  ports:
  - protocol: "TCP"
    port: 5106
    targetPort: 5106
    nodePort: 32071
  type: NodePort