# Deployment Manifest file for backend Dotnet Application 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: webapp-angular
    tier: backend
    app-version: v2.0.0
spec:
  selector:
    matchLabels:
      app: webapp-angular
      tier: backend
      app-version: v2.0.0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-angular
        tier: backend
        app-version: v2.0.0
    spec:
      containers:
      - image: anvesh35/docker-with-dotnet:dotnet-v0c3a64f
        name: dotnet
        env:
        - name: CORS_ORIGIN_URL
          # This is the URL where frontend Angular is running on with Angular service Nodeport
          value: http://161.35.240.187
        ports:
        - containerPort: 5106
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"