apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetwebapp
  labels:
    app: webapp-angular
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp-angular
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-angular
        tier: backend
    spec:
      containers:
      - image: anvesh35/docker-with-dotnet:dotnet-v1.0.0
        name: dotnet
        ports:
        - containerPort: 5106
          
