version: '3'

services:
  angular:
    image: anvesh35/docker-with-dotnet:angular-v0c3a64f      # Docker image for the Angular application
    ports:
      - "80:4200"                                            # Map port 80 on the host to port 4200 in the container
    networks:
      - my_network                                           # Attach to the custom network named "my_network"
    restart: always                                          # Restart policy for the container
    environment:
      API_URL: http://165.232.144.187:8081

  backend:
    image: anvesh35/docker-with-dotnet:dotnet-v0c3a64f       # Docker image for the backend application
    networks:
      - my_network                                           # Attach to the same "my_network" network
    ports:
      - "8081:5106"                                          # Map port 8081 on the host to port 5106 in the container
    restart: always                                          # Restart policy for the container
    volumes:
      - db_login_data:/app/server/
    environment:
      CORS_ORIGIN_URL: http://165.232.144.187
     
networks:
  my_network:                                                # Define a custom bridge network named "my_network"
    driver: bridge                                           # Use the bridge network driver

volumes:
  db_login_data:                                             # Define a named volume named "db_data2"
