# Service Manifest file for frontend Angular Application 
apiVersion: v1
kind: Service
metadata:
  name: angular-np-svc
spec:
  selector:
    app: webapp-angular
    tier: frontend
    app-version: v2.0.0
  ports:
  - protocol: "TCP"
    port: 4200
    targetPort: 4200
    # If you modify this nodePort, ensure that you also update the CORS_ORIGIN_URL in the dotnet-deploy manifest.
    nodePort: 32070
  type: NodePort