# Deployment Manifest file for frontend Angular Application 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: webapp-angular
    tier: frontend
    app-version: v2.0.0
spec:
  selector:
    matchLabels:
      app: webapp-angular
      tier: frontend
      app-version: v2.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-angular
        tier: frontend
        app-version: v2.0.0
    spec:
      containers:
      - name: angular
        env:
        - name: API_URL
          # # This is the URL where backend Dotnet is running on with Dotnet service Nodeport
          value: http://159.89.136.82:32071
        image: anvesh35/docker-with-dotnet:angular-v0c3a64f
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"
