apiVersion: v1
kind: Service
metadata:
  name: angular-svc
spec:
  selector:
    app: webapp-angular
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 4200
    targetPort: 4200
    nodePort: 32070
  type: NodePort